export const demoProject = {
  topic: "Renewable Energy Technology Adoption and Rural Electrification in Nigeria",
  mainTopic: "Energy, Technology and National Development",
  courseCode: "GNS 102",
  courseTitle: "Use of English & Communication Skills II",
  lecturer: "Mr. J. Okonkwo",
  faculty: "School of Computing",
  department: "Department of General Studies",
  academicLevel: "100 Level",
  groupName: "AGP 22",
  institution: "Federal University of Technology, Akure",
  institutionAddress: "PMB 704, Akure, Ondo State, Nigeria.",
  submissionLine:
    "A Term Paper submitted in fulfilment of the requirements for GNS 102 to Mr. J. Okonkwo of the General Studies Unit, Federal University of Technology, Akure, Ondo State.",
  date: "July 2026",
  members: [
    { sn: 1, surname: "Adebayo", otherName: "Tobiloba Samuel", phone: "08023456781", matric: "AGP/01/7901", role: "Group Leader" },
    { sn: 2, surname: "Chukwu", otherName: "Michelle Adaeze", phone: "07039876542", matric: "AGP/02/7912", role: "Researcher" },
    { sn: 3, surname: "Ibrahim", otherName: "Hauwa Zainab", phone: "09067123489", matric: "AGP/02/7925", role: "Typist" },
    { sn: 4, surname: "Okafor", otherName: "Daniel Chinedu", phone: "08154329876", matric: "AGP/03/7933", role: "Typist" },
    { sn: 5, surname: "Yusuf", otherName: "Aisha Bilikisu", phone: "07019283746", matric: "AGP/04/7941", role: "Editor" },
  ].map((m) => ({ ...m, name: `${m.surname}, ${m.otherName}` })),
  resultsSubtopic: "Renewable Energy Technology Adoption and Rural Electrification in Nigeria",
  discussionSubtopic: "The Role of Renewable Energy Technology in Sustainable Rural Development",
  lecturerInstructions:
    "Follow the FUTA GNS 102 term paper template exactly: cover page with six-column group members table, terms of reference, outline, numbered sections with a 1.1 Aim of the Study, an appendices section, and a references list. Use Times New Roman size 12 with 1-inch margins on all sides.",
};

export const sections = {
  introduction: [
    "Access to reliable and affordable electricity is a foundational requirement for sustainable national development. In Nigeria, however, the persistent shortfall between electricity demand and supply has left large parts of the country — particularly rural communities — either poorly served or entirely disconnected from the national grid (Sambo, 2019). Estimates from the Rural Electrification Agency indicate that more than eighty million Nigerians still lack dependable access to grid electricity, a figure that constrains productivity, education, healthcare delivery and small-scale enterprise across the rural landscape.",
    "The challenge of rural electrification in Nigeria is not merely one of generation capacity. It is also shaped by the geographic dispersion of rural settlements, the high per-kilometre cost of grid extension, and the technical losses associated with long transmission distances (Ohunakin et al., 2020). These structural difficulties have progressively directed policy attention towards decentralised renewable energy technologies — notably solar photovoltaic mini-grids, standalone home systems, small wind installations and biomass digesters — as pragmatic alternatives to conventional grid expansion.",
    "The Federal Government's Nigerian Electrification Project, the Energy Transition Plan and the Rural Electrification Strategy and Implementation Plan collectively signal a policy shift toward renewable, off-grid solutions. Development partners including the World Bank and the African Development Bank have also committed substantial funding to accelerate mini-grid deployment (Ogunlana & Adekunle, 2021). Yet the pace and quality of adoption at community level remain uneven, and the practical outcomes of these interventions are still not well understood in the empirical literature.",
    "This paper therefore situates itself at the intersection of renewable energy technology, rural development policy and the lived experience of unserved communities. It examines how emerging renewable technologies are being adopted, financed and integrated into rural electrification programmes in Nigeria, and interrogates the extent to which these interventions are translating into measurable improvements in electricity access.",
    "1.1 AIM OF THE STUDY",
    "This study aims to critically examine the adoption of renewable energy technologies and their role in advancing rural electrification in Nigeria. The specific objectives are to identify the dominant renewable technologies currently being deployed in rural contexts; to evaluate the effectiveness of the policy, financing and implementation frameworks that support their adoption; and to analyse the socioeconomic, technical and institutional challenges that shape outcomes on the ground. Ultimately, the paper seeks to provide an evidence-based assessment that can inform practitioners, policy makers and community stakeholders working to close Nigeria's rural energy access gap.",
  ],
  literature: [
    "The scholarly discourse on renewable energy adoption in developing economies has evolved considerably over the last two decades. Early studies focused predominantly on the technical potential of renewable resources, with Sambo (2019) providing a foundational assessment of Nigeria's solar irradiance, wind regimes and small-hydro capacity, and concluding that the country possesses more than sufficient natural endowment to meet its rural electricity demand.",
    "More recent work has shifted the analytical frame from resource potential to deployment outcomes. Ohunakin et al. (2020) argue that the binding constraints on rural electrification are less technical than institutional: weak enforcement of tariff regimes, unclear regulatory boundaries between the federal Rural Electrification Agency and state governments, and limited capacity within local operators. Their multi-state study of solar mini-grids found that projects governed by clear community ownership arrangements achieved sustainability rates almost three times higher than those managed exclusively by external contractors.",
    "The financing dimension has attracted parallel attention. Ogunlana and Adekunle (2021) mapped forty rural energy financing schemes across West Africa and reported that blended finance instruments — combining concessional capital with results-based grants — produced the strongest deployment outcomes. In Nigeria specifically, the Nigeria Electrification Project's performance-based grant window has been credited with accelerating the pace of mini-grid commissioning, though concerns about affordability for the poorest rural households persist.",
    "A smaller but growing body of Nigerian scholarship has examined the socio-technical dynamics of adoption. Adeoye (2022) uses a household-survey design across five northern states to show that willingness to adopt solar home systems is strongly conditioned by after-sales service availability, warranty enforcement and locally trained technicians, rather than by upfront cost alone. Complementary work by Uzoh and Bello (2023) highlights the gendered dimension of adoption, noting that programmes with explicit female-inclusion strategies achieve higher and more equitable usage outcomes.",
    "Collectively, the literature converges on three propositions: Nigeria's renewable resource base is more than adequate; the deployment gap is driven primarily by institutional, financing and human-capacity constraints; and sustainable outcomes require integrated technical, social and governance interventions. This paper builds on that convergence by examining recent Nigerian evidence within a single analytical frame.",
  ],
  methodology: [
    "This study adopted a mixed-methods design combining a structured desk review with primary qualitative fieldwork. The approach was chosen to allow triangulation between documented programme evidence and the operational realities reported by community-level stakeholders.",
    "The desk review examined policy documents, implementation reports and peer-reviewed studies published between 2018 and 2025, drawn from the Rural Electrification Agency, the Federal Ministry of Power, multilateral development banks and reputable academic databases. A total of forty-two documents met the inclusion criteria and were coded thematically for policy intent, deployment scale, technology mix and reported outcomes.",
    "The qualitative fieldwork consisted of eighteen semi-structured interviews conducted across three geopolitical zones (South-West, North-Central and South-East). Interviewees included mini-grid operators, community energy committee members, Rural Electrification Agency officers and end-user households. Interview guides mirrored the appendices at the end of this paper and were piloted before full deployment.",
    "Data were analysed following Braun and Clarke's (2006) six-phase thematic analysis approach, with codes iteratively refined against the desk-review evidence. Ethical clearance was obtained from the Federal University of Technology, Akure, and all participants provided informed consent. Findings were validated through a member-checking session held virtually with a subset of the interviewees.",
  ],
  results: [
    "The desk review and fieldwork together produced a coherent picture of renewable energy adoption in rural Nigeria. Solar photovoltaic technology dominates the deployment mix, accounting for approximately eighty-seven per cent of the rural installations documented in the reviewed programmes. Small-hydro and biomass contribute the remainder, with utility-scale wind essentially absent from the current rural portfolio.",
    "In terms of deployment scale, the reviewed programmes have collectively commissioned more than one hundred and twenty mini-grids and over one million standalone solar home systems since 2019. Uptake is geographically uneven: the North-East and North-West regions account for the largest number of home system deployments, while the South-East hosts a disproportionate share of productive-use mini-grids serving agro-processing clusters.",
    "The fieldwork revealed a persistent gap between installation and effective service delivery. Fourteen of the eighteen interviewees reported that at least one nearby renewable installation had experienced extended downtime within the previous twelve months, most commonly due to inverter failure, battery degradation or the absence of a local technician certified to perform repairs. Communities with an active energy committee, formal tariff-collection process and contracted maintenance provider consistently reported better service uptime.",
    "Financial data from the reviewed programmes indicate that blended finance instruments — combining concessional debt, performance-based grants and end-user contributions — supported the majority of successful mini-grid deployments. However, affordability remained a binding constraint for the lowest-income households, with roughly one in three interviewed households reporting that they had reduced their consumption to remain within a payable monthly bill.",
  ],
  discussion: [
    "The evidence points to a rural electrification landscape in Nigeria that is technically feasible, policy-supported and increasingly well-funded, yet still constrained by operational and institutional weaknesses. The dominance of solar photovoltaic technology is unsurprising given Nigeria's irradiance profile and the falling cost curve of photovoltaic components, and it corroborates the resource assessments of Sambo (2019). What is more instructive is the concentration of downtime and dropout at the operations-and-maintenance layer rather than at the installation layer.",
    "This pattern supports the argument advanced by Ohunakin et al. (2020) that the binding constraints on rural electrification in Nigeria are predominantly institutional. Programmes that pair technology deployment with structured community ownership, transparent tariff arrangements and locally trained technicians consistently outperform those that treat electrification as a one-off construction project. The consistency of this finding across zones suggests it is not a regional artefact but a general design principle.",
    "The finance data reinforce a related observation. Blended finance can bridge the affordability gap between commercial viability and end-user payability, but only when accompanied by robust results-based verification. Without such verification, incentives skew toward installations that are technically complete but operationally fragile. The Nigeria Electrification Project's performance-based grant mechanism therefore represents an important step, though its reach is still limited relative to the scale of the access deficit.",
    "The gendered adoption pattern noted by Uzoh and Bello (2023) also merits emphasis. Where women are formally represented on energy committees and included in technician training pipelines, service outcomes improve materially. This suggests that inclusion is not only an equity consideration but an operational one that directly shapes programme sustainability.",
  ],
  conclusion: [
    "This paper set out to examine the adoption of renewable energy technologies and their role in advancing rural electrification in Nigeria. Drawing on a desk review of forty-two policy and academic sources and eighteen field interviews across three geopolitical zones, it has shown that renewable technologies — dominated by solar photovoltaics — are now the principal vehicle for extending electricity access to unserved rural communities.",
    "The evidence indicates that Nigeria's renewable resource base and policy framework are adequate to meet the rural electrification challenge in principle. The deployment gap is driven primarily by weaknesses in operations, maintenance, community governance and finance-linked accountability. Addressing these institutional constraints — rather than adding further capacity in isolation — is the highest-leverage pathway to durable outcomes.",
    "The paper therefore recommends that future rural electrification programmes in Nigeria be designed as integrated socio-technical interventions: pairing every installation with a defined operations-and-maintenance contract, an accountable community energy committee, a locally certified technician pipeline and a transparent, verifiable financing structure. Such an approach offers the most credible route to translating Nigeria's renewable energy potential into sustained electricity access for its rural population.",
  ],
  appendices: [
    "The following guiding questions formed the basis of the semi-structured interviews and stakeholder consultations conducted for this study.",
    "1. Which renewable energy technologies are currently deployed in your community or programme area, and how were they selected?",
    "2. What financing arrangements — grants, loans, tariffs, community contributions — support the installation and continued operation of these systems?",
    "3. What operational challenges (downtime, spare parts, technician availability, tariff collection) have you experienced in the last twelve months?",
    "4. How are community members, and women in particular, involved in the governance and day-to-day operation of the installation?",
    "5. What changes in productive activity, education, healthcare or household welfare have you observed since the installation became operational?",
    "6. In your view, what single change would most improve rural electrification outcomes in Nigeria?",
  ],
  references: [
    "Adeoye, O. (2022). Household determinants of solar home system adoption in northern Nigeria. Nigerian Journal of Energy and Development, 14(2), 87–104.",
    "Braun, V., & Clarke, V. (2006). Using thematic analysis in psychology. Qualitative Research in Psychology, 3(2), 77–101.",
    "Ogunlana, A., & Adekunle, T. (2021). Blended finance and rural energy access in West Africa: A comparative review. West African Journal of Infrastructure Studies, 9(1), 33–58.",
    "Ohunakin, O. S., Adaramola, M. S., Oyewola, O. M., & Fagbenle, R. O. (2020). Institutional determinants of solar mini-grid sustainability in Nigeria. Renewable and Sustainable Energy Reviews, 132, 110045.",
    "Sambo, A. S. (2019). Renewable energy resource assessment and rural electrification in Nigeria. Nigerian Journal of Renewable Energy, 22(3), 1–20.",
    "Uzoh, C., & Bello, F. (2023). Gender inclusion and outcomes in rural energy programmes: Evidence from Nigeria. Journal of African Development Studies, 11(4), 201–223.",
  ],
  outline: [
    { n: "", t: "TITLE PAGE" },
    { n: "1.0", t: "Introduction" },
    { n: "1.1", t: "Aim of the Study" },
    { n: "2.0", t: "Literature Review" },
    { n: "3.0", t: "Methodology" },
    { n: "4.0", t: "Results" },
    { n: "4.1", t: "Renewable Energy Technology Adoption and Rural Electrification in Nigeria" },
    { n: "5.0", t: "Discussion" },
    { n: "5.1", t: "The Role of Renewable Energy Technology in Sustainable Rural Development" },
    { n: "6.0", t: "Conclusion" },
    { n: "7.0", t: "Appendices" },
    { n: "", t: "References" },
  ],
};
