/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiExportPdfRouteImport } from './routes/api/export/pdf'
import { Route as ApiExportDocxRouteImport } from './routes/api/export/docx'
import { Route as AuthenticatedPaperIdRouteImport } from './routes/_authenticated/paper.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin/projects'
import { Route as AuthenticatedAdminHelpRouteImport } from './routes/_authenticated/admin/help'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiExportPdfRoute = ApiExportPdfRouteImport.update({
  id: '/api/export/pdf',
  path: '/api/export/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportDocxRoute = ApiExportDocxRouteImport.update({
  id: '/api/export/docx',
  path: '/api/export/docx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPaperIdRoute = AuthenticatedPaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHelpRoute = AuthenticatedAdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$code': typeof RCodeRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/paper/$id': typeof AuthenticatedPaperIdRoute
  '/api/export/docx': typeof ApiExportDocxRoute
  '/api/export/pdf': typeof ApiExportPdfRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$code': typeof RCodeRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/paper/$id': typeof AuthenticatedPaperIdRoute
  '/api/export/docx': typeof ApiExportDocxRoute
  '/api/export/pdf': typeof ApiExportPdfRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$code': typeof RCodeRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/help': typeof AuthenticatedAdminHelpRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/paper/$id': typeof AuthenticatedPaperIdRoute
  '/api/export/docx': typeof ApiExportDocxRoute
  '/api/export/pdf': typeof ApiExportPdfRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin'
    | '/account'
    | '/dashboard'
    | '/new'
    | '/invite/$token'
    | '/r/$code'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/help'
    | '/admin/projects'
    | '/admin/users'
    | '/paper/$id'
    | '/api/export/docx'
    | '/api/export/pdf'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/register'
    | '/account'
    | '/dashboard'
    | '/new'
    | '/invite/$token'
    | '/r/$code'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/help'
    | '/admin/projects'
    | '/admin/users'
    | '/paper/$id'
    | '/api/export/docx'
    | '/api/export/pdf'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/invite/$token'
    | '/r/$code'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/help'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/users'
    | '/_authenticated/paper/$id'
    | '/api/export/docx'
    | '/api/export/pdf'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RCodeRoute: typeof RCodeRoute
  ApiExportDocxRoute: typeof ApiExportDocxRoute
  ApiExportPdfRoute: typeof ApiExportPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/export/pdf': {
      id: '/api/export/pdf'
      path: '/api/export/pdf'
      fullPath: '/api/export/pdf'
      preLoaderRoute: typeof ApiExportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/docx': {
      id: '/api/export/docx'
      path: '/api/export/docx'
      fullPath: '/api/export/docx'
      preLoaderRoute: typeof ApiExportDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/paper/$id': {
      id: '/_authenticated/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof AuthenticatedPaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/help': {
      id: '/_authenticated/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AuthenticatedAdminHelpRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminHelpRoute: typeof AuthenticatedAdminHelpRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminHelpRoute: AuthenticatedAdminHelpRoute,
    AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPaperIdRoute: typeof AuthenticatedPaperIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPaperIdRoute: AuthenticatedPaperIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  RCodeRoute: RCodeRoute,
  ApiExportDocxRoute: ApiExportDocxRoute,
  ApiExportPdfRoute: ApiExportPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
