// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsplunwjcsttnlixkrfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcGx1bndqY3N0dG5saXhrcmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MjAwMjIsImV4cCI6MjEwMDQ5NjAyMn0.ojY-E8ocZPyB0cPVe8WZ6krAh4yxs7JDNgDrSGY-mec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});